server:
  port: 8081
spring:
  application:
    name: sql-web
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tc
    username: root
    password: 3852159
  cloud:
    nacos:
      server-addr: localhost:8848
dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: sql-parse
  consumer:
    check: false

