server:
  port: 8081
spring:
  application:
    name: sql
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mvc:
    static-path-pattern: /static/**